### PR TITLE
Fix job id in link

### PR DESCRIPTION
**Pull request by bdpiparva**
Freemarker renders numbers based on the locale. which is for human readers (like 3000000 is possibly printed as 3,000,000). To avoid formatting of number it should be used with ${x?c} instead of ${x}

### CODE REVIEW

**Comment by GaneshSPatil** [comment]
@bdpiparva -- can we revert the whitespace (indent) changes from the template?

**Comment by bdpiparva** [comment]
It was not indented properly so first commit I made was to indent it properly.

**Comment by GaneshSPatil** [comment]
Okay, we might need to fix the indentation for [docker-swarm-elastic-agent-plugin](https://github.com/gocd-contrib/docker-swarm-elastic-agent-plugin/blob/master/src/main/resources/profile.template.html) as well.

Not sure if there are any other plugins using `8 spaces` indentation.

**Comment by GaneshSPatil** [comment]
Also, 
Do we need this fix for other plugins too?
- [docker-elastic-agents](https://github.com/gocd-contrib/docker-elastic-agents-plugin/blob/master/src/main/resources/status-report.template.ftlh#L148)
- [docker-swarm-elastic-agent-plugin](https://github.com/gocd-contrib/docker-swarm-elastic-agent-plugin/blob/master/src/main/resources/status-report.template.ftlh#L291)

**Comment by bdpiparva** [comment]
@GaneshSPatil  - Yes when we work on those plugin we should indent the code

**Pull request merged**
