### PR TITLE
Upgrade to the latest Kubernetes Client

### PR DESCRIPTION
**Pull request by JamesMcNee**
Upgrade to the latest version of the kubernetes-client library and disable auto configuration.

Fixes: https://github.com/gocd/kubernetes-elastic-agents/issues/347

### CODE REVIEW

**Comment by chadlwilson** [comment]
Thanks for this, will take a look. I'd been meaning to take a look at the client upgrade (I'd already done it on the sister kubernetes-secrets plugin but there was something in the changelog here that concerned me for some reason. Will take a look at your changes and try and recollect 😅

**Comment by chadlwilson** [comment]
Thanks, made a couple of minor tweaks, but this seems to be working fine.

**Comment by chadlwilson** [comment]
https://github.com/gocd/kubernetes-elastic-agents/releases/tag/v3.9.0-420

**Comment by JamesMcNee** [comment]
Thanks very much @chadlwilson!

**Comment by chadlwilson** [comment]
FYI, the underlying bug in the client with auto config and automatic token refresh is fixed now, and I've intentionally re-enabled this to reduce config needs if the plugin in many cases in #386 - should have no effect on most folks, but if you want to give it a go it'd be appreciated.

**Comment by JamesMcNee** [comment]
Hey Chad, thanks for the heads up, sure we can give it a go shortly 👍

**Comment by chadlwilson** [comment]
If youre interested in how they fixed the underlying bug you worked around, they introduced `autoOauthToken` independent of `oauthToken` so that any autorefeshed token from a provider or auto configuration would never be able to override a hard set token from the user.

**Comment by chris-gillatt** [comment]
> FYI, the underlying bug in the client with auto config and automatic token refresh is fixed now, and I've intentionally re-enabled this to reduce config needs of the plugin in many cases in #386 - should have no effect on most folks, but if you want to give it a go it'd be appreciated.

I can confirm that kubernetes-elastic-agent `4.0.0-505` works well with no credential issues on GoCD `23.5.0`.  Thanks all.

**Pull request merged**
